"""
Tests for schema SAID verification (Phase 3).

fetch_and_verify_schema() makes a real HTTP call, so all tests that
exercise it mock requests.get. verify_schema_said() is pure and
tested without mocking.
"""
import copy
from unittest.mock import MagicMock, patch

import pytest

from src.schema import (
    SCHEMA_TYPES,
    fetch_and_verify_schema,
    resolve_credential_type,
    verify_schema_said,
)

# A minimal schema with a correct, pre-computed SAID.
# Generated by: Saider.saidify(sad=schema, label=Saids.dollar)
VALID_SCHEMA = {
    "$id": "EEe6L3kmXv3FCfI27_Niu9Nbd6gqEaznghUcHSrkabp4",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ECR Auth",
    "description": "Engagement Context Role credential schema (test fixture)",
    "type": "object",
    "properties": {
        "LEI": {"type": "string"},
        "personLegalName": {"type": "string"},
        "engagementContextRole": {"type": "string"},
    },
    "required": ["LEI", "personLegalName", "engagementContextRole"],
}
VALID_SAID = VALID_SCHEMA["$id"]


class TestResolveCredentialType:
    def test_qvi_schema(self):
        assert resolve_credential_type("EBfdlu8R27Fbx-ehrqwImnyjnB2YpMgOEOs9OkdeKFzw") == "QVI"

    def test_le_schema(self):
        assert resolve_credential_type("ENPXp1vQzRF6ELV5kl2uraw4MrmsTXgng1xdt4n2pHfn") == "LE"

    def test_oor_schema(self):
        assert resolve_credential_type("EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy") == "OOR"

    def test_ecr_schema(self):
        assert resolve_credential_type("EEy9PkikFcANV1l7EHukCeXqrzT1hNZjGlUk7wuMO5jw") == "ECR"

    def test_unknown_schema_returns_unknown(self):
        assert resolve_credential_type("EBfdlu8R27Fbx-ehrqwImnyjnB2YpMgOEOs9OkdeKFzX") == "Unknown"

    def test_all_known_saids_are_mapped(self):
        assert len(SCHEMA_TYPES) == 4


class TestVerifySchemaSaid:
    def test_valid_schema_passes(self):
        assert verify_schema_said(VALID_SCHEMA, VALID_SAID) is True

    def test_tampered_field_fails(self):
        bad = copy.deepcopy(VALID_SCHEMA)
        bad["title"] = "Tampered Title"
        assert verify_schema_said(bad, VALID_SAID) is False

    def test_wrong_expected_said_fails(self):
        wrong_said = "EBfdlu8R27Fbx-ehrqwImnyjnB2YpMgOEOs9OkdeKFzw"
        assert verify_schema_said(VALID_SCHEMA, wrong_said) is False

    def test_missing_id_field_fails(self):
        bad = copy.deepcopy(VALID_SCHEMA)
        del bad["$id"]
        assert verify_schema_said(bad, VALID_SAID) is False

    def test_empty_dict_fails(self):
        assert verify_schema_said({}, VALID_SAID) is False


class TestFetchAndVerifySchema:
    def _mock_response(self, status_code: int = 200, json_data: dict = None):
        mock = MagicMock()
        mock.status_code = status_code
        mock.json.return_value = json_data if json_data is not None else VALID_SCHEMA
        return mock

    @patch("src.schema.requests.get")
    def test_valid_response_passes(self, mock_get):
        mock_get.return_value = self._mock_response(200, VALID_SCHEMA)
        assert fetch_and_verify_schema(VALID_SAID) is True

    @patch("src.schema.requests.get")
    def test_http_404_fails(self, mock_get):
        mock_get.return_value = self._mock_response(404)
        assert fetch_and_verify_schema(VALID_SAID) is False

    @patch("src.schema.requests.get")
    def test_http_500_fails(self, mock_get):
        mock_get.return_value = self._mock_response(500)
        assert fetch_and_verify_schema(VALID_SAID) is False

    @patch("src.schema.requests.get")
    def test_tampered_schema_content_fails(self, mock_get):
        bad = copy.deepcopy(VALID_SCHEMA)
        bad["title"] = "Tampered"
        mock_get.return_value = self._mock_response(200, bad)
        assert fetch_and_verify_schema(VALID_SAID) is False

    @patch("src.schema.requests.get")
    def test_network_error_fails(self, mock_get):
        import requests as req
        mock_get.side_effect = req.RequestException("connection refused")
        assert fetch_and_verify_schema(VALID_SAID) is False

    @patch("src.schema.requests.get")
    def test_correct_url_is_called(self, mock_get):
        mock_get.return_value = self._mock_response(200, VALID_SCHEMA)
        fetch_and_verify_schema(VALID_SAID)
        expected_url = f"https://schema.vlei.dev/oobi/{VALID_SAID}"
        mock_get.assert_called_once_with(expected_url, timeout=10)
