"""
Tests for SAID verification (Phase 1).

Uses synthetic fixtures generated by scripts/make_fixtures.py.
No network required — all credentials are pre-computed locally.
"""
import copy
import json
import pathlib

import pytest

from src.said import verify_said

FIXTURES = pathlib.Path(__file__).parent.parent / "fixtures"


@pytest.fixture
def ecr() -> dict:
    return json.loads((FIXTURES / "sample_ecr.json").read_text())


@pytest.fixture
def le() -> dict:
    return json.loads((FIXTURES / "sample_le.json").read_text())


@pytest.fixture
def qvi() -> dict:
    return json.loads((FIXTURES / "sample_qvi.json").read_text())


class TestVerifySaid:
    def test_valid_ecr(self, ecr):
        assert verify_said(ecr) is True

    def test_valid_le(self, le):
        assert verify_said(le) is True

    def test_valid_qvi(self, qvi):
        assert verify_said(qvi) is True

    def test_tampered_d_field(self, ecr):
        """Replacing the d field with a different SAID must fail."""
        bad = copy.deepcopy(ecr)
        bad["d"] = "EBfdlu8R27Fbx-ehrqwImnyjnB2YpMgOEOs9OkdeKFzw"
        assert verify_said(bad) is False

    def test_tampered_attribute(self, ecr):
        """Modifying any data field must invalidate the SAID."""
        bad = copy.deepcopy(ecr)
        bad["a"]["personLegalName"] = "Attacker Name"
        assert verify_said(bad) is False

    def test_tampered_issuer(self, ecr):
        bad = copy.deepcopy(ecr)
        bad["i"] = "EDP1vHcw_wc4M__Fj53-cJaBnZZASd-aN0-oZe4kHsSi"
        assert verify_said(bad) is False

    def test_missing_d_field(self, ecr):
        bad = copy.deepcopy(ecr)
        del bad["d"]
        assert verify_said(bad) is False

    def test_missing_v_field(self, ecr):
        bad = copy.deepcopy(ecr)
        del bad["v"]
        assert verify_said(bad) is False

    def test_empty_dict(self):
        assert verify_said({}) is False
