"""
Generate synthetic ACDC fixture credentials for tests.

These credentials have valid, self-consistent SAIDs and use real KERI AIDs
generated by keripy Habs so all CESR encodings are valid.
No network required — everything runs locally.
Run once: python scripts/make_fixtures.py
"""
import json
import pathlib

from keri import Protocols, Kinds, versify
from keri.core import Saider, MtrDex
from keri.core.coring import Saids
from keri.app import habbing

FIXTURES = pathlib.Path(__file__).parent.parent / "fixtures"

# Known vLEI schema SAIDs (testnet) — verify against GLEIF schema server before use
SCHEMA_QVI = "EBfdlu8R27Fbx-ehrqwImnyjnB2YpMgOEOs9OkdeKFzw"
SCHEMA_LE  = "ENPXp1vQzRF6ELV5kl2uraw4MrmsTXgng1xdt4n2pHfn"
SCHEMA_ECR = "EEy9PkikFcANV1l7EHukCeXqrzT1hNZjGlUk7wuMO5jw"

REGISTRY_SAID = "EBfMDFWxNHYCQ4jbTnmFMwc2N2gHbA6N8LF1LFkpGMek"
ISO_DT        = "2024-01-15T12:00:00.000000+00:00"


def saidify_block(block: dict) -> dict:
    """Compute and fill the SAID (d field) of a sub-block."""
    _, saidified = Saider.saidify(sad=block, code=MtrDex.Blake3_256, label=Saids.d)
    return saidified


def build_cred(issuer_aid: str, schema: str, attribs: dict, edges: dict | None = None) -> dict:
    """Build and saidify a top-level ACDC credential dict."""
    cred = dict(
        v=versify(proto=Protocols.acdc, kind=Kinds.json, size=0),
        d="",
        i=issuer_aid,
        ri=REGISTRY_SAID,
        s=schema,
        a=attribs,
    )
    if edges is not None:
        cred["e"] = edges
    _, saidified = Saider.saidify(sad=cred, code=MtrDex.Blake3_256, label=Saids.d)
    return saidified


def main():
    FIXTURES.mkdir(exist_ok=True)

    # Generate four real KERI AIDs so CESR encoding is always valid
    with habbing.openHby(name="fixtures", temp=True) as hby:
        gleif_hab   = hby.makeHab(name="gleif")
        qvi_hab     = hby.makeHab(name="qvi")
        le_hab      = hby.makeHab(name="le")
        subject_hab = hby.makeHab(name="subject")

        gleif_aid   = gleif_hab.pre
        qvi_aid     = qvi_hab.pre
        le_aid      = le_hab.pre
        subject_aid = subject_hab.pre

        # QVI credential — issued by GLEIF root, no edges
        qvi_attribs = saidify_block(dict(
            d="",
            i=qvi_aid,
            dt=ISO_DT,
            LEI="254900OPPU84GM83MG36",
        ))
        qvi_cred = build_cred(
            issuer_aid=gleif_aid,
            schema=SCHEMA_QVI,
            attribs=qvi_attribs,
        )

        # LE credential — issued by QVI AID, edges to QVI credential
        le_attribs = saidify_block(dict(
            d="",
            i=le_aid,
            dt=ISO_DT,
            LEI="254900OPPU84GM83MG36",
            legalName="Example Corp Ltd",
        ))
        le_edges = saidify_block(dict(
            d="",
            qvi=dict(n=qvi_cred["d"], s=SCHEMA_QVI),
        ))
        le_cred = build_cred(
            issuer_aid=qvi_aid,
            schema=SCHEMA_LE,
            attribs=le_attribs,
            edges=le_edges,
        )

        # ECR credential — issued by LE AID, edges to LE credential
        ecr_attribs = saidify_block(dict(
            d="",
            i=subject_aid,
            dt=ISO_DT,
            LEI="254900OPPU84GM83MG36",
            personLegalName="Jane Smith",
            engagementContextRole="Chief Financial Officer",
        ))
        ecr_edges = saidify_block(dict(
            d="",
            le=dict(n=le_cred["d"], s=SCHEMA_LE),
        ))
        ecr_cred = build_cred(
            issuer_aid=le_aid,
            schema=SCHEMA_ECR,
            attribs=ecr_attribs,
            edges=ecr_edges,
        )

    chain = {
        "files": [
            "fixtures/sample_ecr.json",
            "fixtures/sample_le.json",
            "fixtures/sample_qvi.json",
        ],
        "gleif_root": gleif_aid,
    }

    (FIXTURES / "sample_qvi.json").write_text(json.dumps(qvi_cred, indent=2))
    (FIXTURES / "sample_le.json").write_text(json.dumps(le_cred, indent=2))
    (FIXTURES / "sample_ecr.json").write_text(json.dumps(ecr_cred, indent=2))
    (FIXTURES / "chain.json").write_text(json.dumps(chain, indent=2))

    print("Fixtures written:")
    for name in ("sample_qvi.json", "sample_le.json", "sample_ecr.json", "chain.json"):
        print(f"  fixtures/{name}")

    print(f"\nAIDs used:")
    print(f"  GLEIF root : {gleif_aid}")
    print(f"  QVI        : {qvi_aid}")
    print(f"  LE         : {le_aid}")
    print(f"  Subject    : {subject_aid}")

    print(f"\nSAIDs:")
    print(f"  QVI : {qvi_cred['d']}")
    print(f"  LE  : {le_cred['d']}")
    print(f"  ECR : {ecr_cred['d']}")


if __name__ == "__main__":
    main()
